#!/usr/bin/env bash

docker_image="itsnotsimple/quick-slate"
docker_container_name="quickslate_app"
slate_source_path="slate/source"
slate_build_path="slate/build"

perform_start () {
  docker run -p 4567:4567 -v $root/${slate_source_path}:/slate/source \
   -v $root/${slate_build_path}:/slate/build \
   -d --name ${docker_container_name} ${docker_image}
}

perform_stop () {
  docker stop ${docker_container_name} > /dev/null
}

perform_container_clean () {
  docker container rm ${docker_container_name}
}

perform_build () {
  docker exec ${docker_container_name} /bin/bash -c "cd slate;bundle exec middleman build"
}